services:
  - type: web
    name: rusd-airdrop
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8002
      - key: ANCHOR_PROVIDER_URL
        value: https://api.devnet.solana.com
      - key: ANCHOR_WALLET
        sync: false
    healthCheckPath: /
